services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${APP_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_DB: ${APP_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local